---
# tasks file for sysdev.openshift

- name: download and untar openshift
  unarchive:
    src: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz"
    copy: no
    dest: "/tmp"
- name: move openshift to usr/local/sbin
  shell: mv k* o* /usr/local/sbin/
  args:
    chdir: /tmp/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit
- name: start cluster
  shell: /usr/local/sbin/oc cluster up --public-hostname={{ inventory_hostname }}

